server:
  port: 31001
  servlet:
    context-path: /TtTools
    session:
      timeout: 1800
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tools?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT
    username: root
    password: root
    driver-calss-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true